# Generated by Django 3.2.3 on 2021-06-02 09:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('price', models.IntegerField(default=0)),
                ('discription', models.CharField(default='', max_length=400)),
                ('image', models.ImageField(upload_to='products/')),
            ],
        ),
    ]
