# Generated by Django 3.2.3 on 2021-06-05 07:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0003_catagory'),
    ]

    operations = [
        migrations.RenameField(
            model_name='catagory',
            old_name='price',
            new_name='cid',
        ),
        migrations.RemoveField(
            model_name='catagory',
            name='discription',
        ),
        migrations.RemoveField(
            model_name='catagory',
            name='image',
        ),
    ]
