# Generated by Django 3.2.3 on 2021-06-05 07:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0004_auto_20210605_1234'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='catagory',
            name='cid',
        ),
    ]
