# Generated by Django 3.2.3 on 2021-06-05 07:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0005_remove_catagory_cid'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='Catagory',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='books.catagory'),
        ),
    ]
