# Generated by Django 3.2.3 on 2021-06-07 15:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0006_product_catagory'),
    ]

    operations = [
        migrations.CreateModel(
            name='MainImages',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='uploads/comics')),
            ],
        ),
        migrations.AlterField(
            model_name='product',
            name='discription',
            field=models.CharField(blank=True, default='', max_length=400, null=True),
        ),
    ]
