# Generated by Django 3.2.3 on 2021-06-18 06:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0007_auto_20210607_2038'),
    ]

    operations = [
        migrations.CreateModel(
            name='Costomer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=254)),
                ('password', models.CharField(max_length=500)),
                ('confirm_password', models.CharField(max_length=500)),
                ('number', models.CharField(max_length=10)),
            ],
        ),
        migrations.DeleteModel(
            name='MainImages',
        ),
    ]
