# Generated by Django 3.2.3 on 2021-06-19 06:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0008_auto_20210618_1222'),
    ]

    operations = [
        migrations.AlterField(
            model_name='costomer',
            name='number',
            field=models.IntegerField(max_length=10),
        ),
    ]
