# Generated by Django 3.2.3 on 2021-06-19 06:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0009_alter_costomer_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='costomer',
            name='number',
            field=models.IntegerField(blank=True, max_length=10, null=True),
        ),
    ]
