# Generated by Django 3.2.3 on 2021-06-20 05:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0011_alter_costomer_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='costomer',
            name='number',
            field=models.CharField(max_length=10, null=True),
        ),
    ]
