# Generated by Django 3.2.3 on 2021-07-04 06:25

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0012_alter_costomer_number'),
    ]

    operations = [
        migrations.CreateModel(
            name='Orders',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(default=1)),
                ('price', models.IntegerField()),
                ('date', models.DateField(default=datetime.datetime.today)),
                ('costomer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='books.costomer')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='books.product')),
            ],
        ),
    ]
