# Generated by Django 3.2.3 on 2021-07-04 06:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0013_orders'),
    ]

    operations = [
        migrations.AddField(
            model_name='orders',
            name='Address',
            field=models.CharField(blank=True, default='', max_length=500),
        ),
        migrations.AddField(
            model_name='orders',
            name='phone',
            field=models.CharField(blank=True, default='', max_length=500),
        ),
    ]
