# Generated by Django 3.2.3 on 2021-07-29 13:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0015_orders_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orders',
            name='costomer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='books.costomer'),
        ),
    ]
