# Generated by Django 3.2.3 on 2021-07-29 13:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0016_alter_orders_costomer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orders',
            name='costomer',
            field=models.ForeignKey(blank=True, default='', null=True, on_delete=django.db.models.deletion.CASCADE, to='books.costomer'),
        ),
    ]
