# Generated by Django 3.2.3 on 2021-08-03 17:05

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0017_alter_orders_costomer'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='artist',
            field=models.CharField(default='S SAKAN', max_length=50),
        ),
        migrations.AddField(
            model_name='product',
            name='penciler',
            field=models.CharField(default='Christopher Moonehyam', max_length=50),
        ),
        migrations.AddField(
            model_name='product',
            name='published',
            field=models.DateField(default=datetime.datetime.today),
        ),
        migrations.AddField(
            model_name='product',
            name='writer',
            field=models.CharField(default='Clay Champman', max_length=50),
        ),
    ]
