# Generated by Django 3.2.3 on 2021-08-04 10:11

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0018_auto_20210803_2235'),
    ]

    operations = [
        migrations.CreateModel(
            name='Movies',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('Mposter', models.ImageField(upload_to='uploads')),
                ('director', models.CharField(max_length=50)),
                ('writer', models.CharField(max_length=50)),
                ('cast', models.CharField(max_length=50)),
                ('producer', models.CharField(max_length=50)),
                ('Exproducer', models.CharField(max_length=50)),
                ('ReleasedDate', models.DateField(default=datetime.datetime.today)),
                ('trailer', models.FileField(null=True, upload_to='uploads')),
                ('description', models.CharField(max_length=50)),
            ],
        ),
    ]
