# Generated by Django 3.2.3 on 2021-08-04 10:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0019_movies'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movies',
            name='Exproducer',
            field=models.CharField(default="Louis D'Esposito, Victoria Alonso and Charles Newirth", max_length=500),
        ),
        migrations.AlterField(
            model_name='movies',
            name='cast',
            field=models.CharField(default='Simu Liu, Awkwafina, Tony Leung, Michelle Yeoh, Fala Chen, Meng’er Zhang, Florian Munteanu and Ronny Chieng', max_length=500),
        ),
        migrations.AlterField(
            model_name='movies',
            name='description',
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name='movies',
            name='director',
            field=models.CharField(default='Destin Daniel Cretton', max_length=500),
        ),
        migrations.AlterField(
            model_name='movies',
            name='name',
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name='movies',
            name='producer',
            field=models.CharField(default='Kevin Feige and Jonathan Schwartz', max_length=500),
        ),
        migrations.AlterField(
            model_name='movies',
            name='writer',
            field=models.CharField(default='David Callaham, Destin Daniel Cretton and Andrew Lanham', max_length=500),
        ),
    ]
